# Setup
url: https://uranuno.github.io
lang: "ja"
title: '@uranuno'
description: 開発などのメモです
author:
  id: uranuno
  name: "yumi nunoura"
  email: "uranuno@gmail.com"

# Outputting
permalink: pretty
# excerpt_separator: "<!-- more -->"

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Theme
remote_theme: jekyll/minima

minima:
  skin: solarized

  date_format: "%b %d, %Y"

  social_links:
    - { platform: github, user_url: "https://github.com/uranuno" }
    - { platform: twitter, user_url: "https://twitter.com/uranuno" }
    - { platform: instagram, user_url: "https://www.instagram.com/uranuno" }
