# Setup
lang: ja
title: "@uranuno"
description: 開発などのメモです

# Outputting
permalink: pretty

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme
remote_theme: jekyll/minima

minima:
  skin: solarized-light

  date_format: "%b %d, %Y"

  social_links:
    - { platform: github, user_url: "https://github.com/uranuno" }
    - { platform: twitter, user_url: "https://twitter.com/uranuno" }
    - { platform: instagram, user_url: "https://www.instagram.com/uranuno" }

# GA
google_analytics: G-9EE9W1BJPQ

# SEO
twitter:
  card: summary

# Defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/default-card.png
