# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            nunomemo
description:      開発メモです。
url:              http://uranuno.github.io/
baseurl:          /
author:           'yumi nunoura'

# Layout
paginate:         5
excerpt_separator: <!-- more -->
