# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            uranuno.github.io
url:              http://uranuno.github.io/
baseurl:          /

author:
  name:           'yumi nunoura'
  url:            https://twitter.com/uranuno

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/uranuno
