# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            nunomemo
description:      開発メモです。
url:              http://uranuno.github.io/
baseurl:          /

# Author
author:
  name:           'yumi nunoura'
  links:
    github:
      url:        https://github.com/uranuno
      icon:       github-alt
    twitter:
      url:        https://twitter.com/uranuno
      icon:       twitter
    pinterest:
      url:        https://jp.pinterest.com/uranuno/
      icon:       pinterest

# Layout
paginate:         5
excerpt_separator: <!-- more -->
