# Serving
host: 0.0.0.0
baseurl: /

# Setup
url: http://uranuno.github.io/
title: nunomemo
description: 開発メモです。
author: "yumi nunoura"

# Outputting
permalink: pretty
excerpt_separator: "<!-- more -->"
paginate: 5

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
