# Serving
host: 0.0.0.0
baseurl: /

# Setup
url: https://uranuno.github.io
title: nunomemo
description: 開発などのメモです
author:
  id: uranuno
  name: "yumi nunoura"
  email: "uranuno@gmail.com"

# Outputting
permalink: pretty
excerpt_separator: "<!-- more -->"
paginate: 5

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Collections
collections:
  tag_labels:
    output: true
    permalink: /tags/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: tag_labels
    values:
      layout: tag
