# Serving
host: 0.0.0.0
baseurl: /

# Setup
url: https://uranuno.github.io
title: nunomemo
description: 開発などのメモです
author:
  id: uranuno
  name: "yumi nunoura"
  email: "uranuno@gmail.com"

# Outputting
permalink: /:year/:month/:day/:title/
excerpt_separator: "<!-- more -->"
paginate: 5

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Collections
collections:
  lists:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: lists
    values:
      layout: list
  - scope:
      path: "posts/misc"
      type: posts
    values:
      hidden: true
