# Setup
lang: ja
title: "@uranuno"
description: "開発などのメモです"

# Outputting
permalink: pretty

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme
remote_theme: "jekyll/minima@eec5a0b"

minima:
  social_links:
    - title: GitHub
      icon: github-alt
      url: "https://github.com/uranuno"
    - title: X
      icon: x-twitter
      url: "https://x.com/uranuno"
    - title: Instagram
      icon: instagram
      url: "https://www.instagram.com/uranuno"

# GA
google_analytics: G-9EE9W1BJPQ

# SEO
twitter:
  card: summary

# Defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/default-card.png
