# Serving
host: 0.0.0.0

# Setup
url: https://uranuno.github.io
title: '@uranuno'
description: 開発などのメモです
author:
  id: uranuno
  name: "yumi nunoura"
  email: "uranuno@gmail.com"

# Outputting
permalink: pretty
excerpt_separator: "<!-- more -->"
paginate: 10

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Collections
collections:
  groups:
    output: true
    permalink: /:categories/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: groups
    values:
      layout: group
